#!/bin/bash

if ! npm run build-registry; then
    echo "Build registry failed. Please fix the issues."
    exit 1
fi

if ! npm run prettier; then
    echo "Prettier failed. Please fix the issues."
    exit 1
fi

echo "All checks passed successfully."
