#!/bin/bash

if ! npm run lint; then
    echo "Linting failed. Please fix the errors."
    exit 1
fi

if ! npm run build; then
    echo "Build failed. Please fix the issues."
    exit 1
fi

# Show version increment menu
echo "Select version increment:"
options=("Patch" "Minor" "Major" "Cancel")
select opt in "${options[@]}"
do
    case $opt in
        "Patch")
            npm version patch
            break
            ;;
        "Minor")
            npm version minor
            break
            ;;
        "Major")
            npm version major
            break
            ;;
        "Cancel")
            echo "Version increment canceled."
            exit 1
            ;;
        *)
            echo "Invalid option."
            ;;
    esac
done

# Add the updated package.json to the commit
git add package.json

# Amend the last commit with the updated package.json
git commit --amend --no-edit

# Push the changes
echo "All checks passed and version updated. Pushing the changes."
exit 0
