// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

export const Index: Record<string, any> = {
  default: {
    breadcrumb: {
      name: 'breadcrumb',
      type: 'registry:ui',
      registryDependencies: ['breadcrumb'],
      files: ['registry/default/ui/breadcrumbs/index.tsx'],
      component: React.lazy(() => import('@/registry/default/ui/breadcrumbs/index.tsx')),
      source: '',
      category: 'undefined',
      subcategory: 'undefined',
      chunks: []
    },
    codeSnippet: {
      name: 'codeSnippet',
      type: 'registry:ui',
      registryDependencies: ['alert-dialog', 'button'],
      files: ['registry/default/ui/codeSnippet/index.tsx'],
      component: React.lazy(() => import('@/registry/default/ui/codeSnippet/index.tsx')),
      source: '',
      category: 'undefined',
      subcategory: 'undefined',
      chunks: []
    },
    utils: {
      name: 'utils',
      type: 'registry:lib',
      registryDependencies: undefined,
      files: ['registry/default/lib/utils.ts'],
      component: React.lazy(() => import('@/registry/default/lib/utils.ts')),
      source: '',
      category: 'undefined',
      subcategory: 'undefined',
      chunks: []
    }
  }
};
